[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
grand_bazaar = "4zoGXwqMyi3ndEGqQ8gDmnmoptbRq78hGX7erA3DBs3K"

[[test.genesis]]
bubblegum = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl_token_metadata.so"

[[test.genesis]]
bubblegum = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "./deps/spl_account_compression.so"

[[test.genesis]]
bubblegum = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "./deps/spl_noop.so"

[[test.genesis]]
bubblegum = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "./deps/bubblegum.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keypairs/testing_pair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
